version: '3.8'

services:
  spacetimedb-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000/tcp" # SpacetimeDB HTTP/WebSocket port
      - "3001:3001/udp" # SpacetimeDB WebRTC port (optional, but good for some setups)
    environment:
      - RUST_LOG=info # For SpacetimeDB server logs
      - DB_NAME=${DB_NAME:-quickstart-chat} # Set DB_NAME from .env or default to quickstart-chat
    volumes:
      - spacetimedb_data:/data # Persist SpacetimeDB data
    env_file:
      - ./server/.env
    networks:
      - spacetimedb_net
    command: sh -c "spacetime start --listen-addr 0.0.0.0:3000 --data-dir /data & sleep 5 && spacetime publish --project-path /app ${DB_NAME:-quickstart-chat} && wait"

  client-web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Vite dev server port
    depends_on:
      - spacetimedb-server
    networks:
      - spacetimedb_net
    environment:
      - NODE_ENV=development

networks:
  spacetimedb_net:
    driver: bridge

volumes:
  spacetimedb_data: